resolver: lts-3.0
flags: {}
packages:
- .
- location:
    git: https://github.com/sseefried/hsSDL2
    commit: e824a16c8374173796b607bf976a45c0f79a121e
- location:
    git: https://github.com/sseefried/hs-cairo
    commit: 922c6fab2d632c220ebd3f07b737e75537bfda70
extra-deps:
    - elerea-2.8.0
    - utf8-string-0.3.8